version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack


  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports:
      - 3366:3306
    environment:
      - DBCONNECTIONSTR = root:123456789@tcp(127.0.0.1:3366)/food_delivery?charset=utf8mb4&parseTime=True&loc=Local
      - S3BUCKETNAME = food-go
      - S3REGION = ap-southeast-1
      - S3APIKEY = AKIAUS2KPLDJUOXE22X2
      - S3SECRETKEY = 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
      - S3DOMAIN = https://d1n632kj3y4onx.cloudfront.net
      - LOGINSECRETKEY= Oksdfksdfhch
#      - MYSQL_ROOT_HOST=${DB_HOST}
#      - DBCONNECTIONSTR=${DBCONNECTIONSTR}
#      - S3BUCKETNAME=${S3BUCKETNAME}
#      - S3REGION=${S3REGION}
#      - S3APIKEY=${S3APIKEY}
#      - S3SECRETKEY=${S3SECRETKEY}
#      - S3DOMAIN=${S3DOMAIN}
#      - LOGINSECRETKEY=${LOGINSECRETKEY}
#      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#      - MYSQL_ALLOW_EMPTY_PASSWORD

    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - fullstack-mysql
    environment:
      - PMA_HOST=fullstack-mysql # Note the "fullstack-mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack


volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge